notifications

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -50,8 +50,17 @@ jobs:
           distribution: 'temurin'
           java-version: '11'
       - name: Check Quality Gates
-        run: ./gradlew sonarqube
-
+        run: |
+                  response=$(curl -s -u "e9c15467e0201e7fbd983301a7ee675dd1940964" \
+                    "http://197.140.142.82:9000//api/qualitygates/project_status?projectKey=project_key")
+                  echo "Response: $response"
+                  status=$(echo "$response" | jq -r '.projectStatus.status')
+                  if [[ "$status" == "ERROR" ]]; then
+                    echo "Quality Gate failed!"
+                    exit 1
+                  else
+                    echo "Quality Gate passed!"
+                  fi
   Build:
     needs: Code-Quality
     runs-on: windows-latest
@@ -74,29 +83,24 @@ jobs:
             build/libs/*.jar
             build/docs/javadoc/**/*
 
-
   Deploy:
     runs-on: ubuntu-latest
     needs: Build
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
-
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: 17
           distribution: temurin
-
       - name: Make gradlew Executable
         run: chmod +x gradlew
-
       - name: Déploiement du fichier jar sur myMavenRepo
         run: ./gradlew publish
         env:
           MYMAVENREPO_USERNAME: ${{ secrets.MYMAVENREPO_USERNAME }}
           MYMAVENREPO_PASSWORD: ${{ secrets.REPO_PASS }}
-
   Notification:
     needs: Deploy
     runs-on: windows-latest
@@ -111,4 +115,3 @@ jobs:
         run: |
           ./gradlew notifySlack
           ./gradlew sendMail
-          
